;;; go-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from go.el

(autoload 'go-play "go" "\
Play a game of GO." t)
(autoload 'go-view-sgf "go" "\
View an SGF file.

(fn &optional FILE)" t)
(register-definition-prefixes "go" '("go-instantiate"))


;;; Generated autoloads from go-api.el

(register-definition-prefixes "go-api" '("defgeneric-w-setf" "go-" "ignoring-unsupported"))


;;; Generated autoloads from go-board.el

(register-definition-prefixes "go-board" '("*autoplay*" "*b" "*go-board-overlays*" "*history*" "*size*" "*t" "*white*" "alive-p" "apply-" "black-piece" "board" "clear-labels" "go-" "make-board" "move-type" "neighbors" "other-color" "pieces-to-board" "player-to-string" "point-of-pos" "remove-dead" "update-display" "white-piece" "with-"))


;;; Generated autoloads from go-board-faces.el

(register-definition-prefixes "go-board-faces" '("go-board-"))


;;; Generated autoloads from go-util.el

(register-definition-prefixes "go-util" '("*go-partial-line*" "aget" "alistp" "char-to-num" "compose" "curry" "ear-muffs" "go-" "indexed" "make-go-insertion-filter" "num-to-char" "pos-to-index" "range" "rpush" "set-aget" "sym-cat" "take" "transpose-array" "un-ear-muffs" "until"))


;;; Generated autoloads from list-buffer.el

(register-definition-prefixes "list-buffer" '("*buffer-" "*enter-function*" "*refresh-function*" "list"))

;;; End of scraped data

(provide 'go-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; go-autoloads.el ends here
