;;; ring-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ring-mode.el

(autoload 'ring-mode "ring-mode" "\
A major mode for the Ring programming language.

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.ring\\'" . ring-mode))
(register-definition-prefixes "ring-mode" '("ring-"))

;;; End of scraped data

(provide 'ring-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ring-mode-autoloads.el ends here
